os: Visual Studio 2015
environment:
    global:
        PROJECT_NAME: Jazz
        RUSTUP_INIT_SKIP_MSVC_CHECK: 1
    matrix:
        - TARGET: x86_64-pc-windows-msvc
          CHANNEL: nightly

install:
    - curl -sSf -o rustup-init.exe https://win.rustup.rs
    - rustup-init.exe --default-host %TARGET% --default-toolchain %CHANNEL% -y
    - set PATH=%PATH%;C:\Users\appveyor\.cargo\bin
    - rustc -Vv
    - cargo -V

before_test:
    - cd %APPVEYOR_BUILD_FOLDER%

test_script:
    - cargo build --verbose
    - cargo test --verbose

# 'cargo test' takes care of building for us, so disable Appveyor's build stage. This prevents
# the "directory does not contain a project or solution file" error.
# source: https://github.com/starkat99/appveyor-rust/blob/master/appveyor.yml#L113
build: false
